reviews:
  enabled: true
  auto_review: true

  auto_review_branches:
    - main
    - develop

  rules:
    - path: 'src/**/*.js'
      level: medium
      comment: true
      suggestions: false
    - path: 'src/**/*.jsx'
      level: medium
      comment: true
      suggestions: true

  summary:
    enabled: true
    style: friendly
